language: php
dist: trusty
sudo: false

matrix:
  fast_finish: true
  include:
    - php: "5.3"
      env: USE_PSALM=0
    - php: "5.4"
      env: USE_PSALM=0
    - php: "5.5"
      env: USE_PSALM=0
    - php: "5.6"
      env: USE_PSALM=1
    - php: "7.0"
      env: USE_PSALM=1
    - php: "7.1"
      env: USE_PSALM=1
    - php: "nightly"
      env: USE_PSALM=1
    - php: "hhvm"
      env: USE_PSALM=1
  allow_failures:
    - php: "nightly"
    - php: "hhvm"

install:
    - composer self-update
    - if [[ $USE_PSALM -eq 1 ]]; then composer require --dev "vimeo/psalm:dev-master"; fi
    - composer update

script:
    - vendor/bin/phpunit
    - php -dmbstring.func_overload=7 vendor/bin/phpunit
    - vendor/bin/phpunit --bootstrap autoload-fast.php
    - php -dmbstring.func_overload=7 vendor/bin/phpunit --bootstrap autoload-fast.php
    - if [[ $USE_PSALM -eq 1 ]]; then vendor/bin/psalm; fi
